.global	ease_inQuarters_l
.global	ease_inQuarters_h
.global	ease_outQuarters_l
.global	ease_outQuarters_h
.global	ease_inHalves_l
.global	ease_inHalves_h
.global	ease_outHalves_l
.global	ease_outHalves_h
.global	ease_inOnes_l
.global	ease_inOnes_h
.global	ease_outOnes_l
.global	ease_outOnes_h
.global	ease_inTwos_l
.global	ease_inTwos_h
.global	ease_outTwos_l
.global	ease_outTwos_h
.global	ease_inFours_l
.global	ease_inFours_h
.global	ease_outFours_l
.global	ease_outFours_h
.global	ease_inEights_l
.global	ease_inEights_h
.global	ease_outEights_l
.global	ease_outEights_h
.global	ease_inSixteens_l
.global	ease_inSixteens_h
.global	ease_outSixteens_l
.global	ease_outSixteens_h
