.global OAM_build00
.global OAM_beginDMA
.global OAM_initSprite0
.global OAM_buildPlayer
.global OAM_buildPause
.global OAM_clearRemaining
.global Sprite0_destination
.global Sprite0_setDestination
.global Sprite0_setSplit
.global OAM_ready
