.globalzp PPU_stack
.globalzp PPU_havePalettesChanged
.globalzp PPU_willVRAMUpdate
.global PPU_init
.global PPU_resetClock
.global PPU_advanceClock
.global PPU_resetScroll
.global PPU_setScroll
.global PPU_updateScroll
.global PPU_renderHUD
.global PPU_waitForSprite0Hit
.global PPU_renderScore
.global PPU_scoreToBuffer
.global PPU_planNMI
.global enableRendering
.global disableRendering
.global renderAllPalettes
.global renderAllTiles
.global PPUMASK
.globalzp currentMaskSettings
