;objects
.globalzp PLAYER_SPRITE
.globalzp LARGE_STAR
.globalzp SPRITE02
.globalzp SPRITE03
.globalzp TARGET_SPRITE
.globalzp HEART_SPRITE
.globalzp SPRITE06
.globalzp SPRITE07
.globalzp SMALL_STAR
.globalzp PLAYER_BEAM
.globalzp SPRITE0A
.globalzp SPRITE0B
.globalzp SPRITE0C
.globalzp SPRITE0D
.globalzp SPRITE0E
.globalzp SPRITE0F
.globalzp SPRITE10
.globalzp SPRITE11
.globalzp SPRITE12
.globalzp SPRITE13
.globalzp SPRITE14
.globalzp SPRITE15
.globalzp SPRITE16
.globalzp SPRITE17
.globalzp SPRITE18
.globalzp SPRITE19
.globalzp SPRITE1A
.globalzp SPRITE1B
.globalzp SPRITE1C
.globalzp SPRITE1D
.globalzp SPRITE1E
.globalzp SPRITE1F
.globalzp SPRITE20
.globalzp SPRITE21

;address table
.global spritesH
.global spritesL
