;objects
.globalzp SPRITE01
.globalzp SPRITE02
.globalzp SPRITE03
.globalzp SPRITE04
.globalzp SPRITE05
.globalzp SPRITE06
.globalzp SPRITE07
.globalzp SPRITE08
.globalzp SPRITE09
.globalzp SPRITE0A
.globalzp SPRITE0B
.globalzp SPRITE0C
.globalzp SPRITE0D
.globalzp SPRITE0E
.globalzp SPRITE0F
.globalzp SPRITE10
.globalzp SPRITE11
.globalzp SPRITE12
.globalzp SPRITE13
.globalzp SPRITE14
.globalzp SPRITE15
.globalzp SPRITE16
.globalzp SPRITE17
.globalzp SPRITE18
.globalzp SPRITE19
.globalzp SPRITE1A
.globalzp SPRITE1B
.globalzp SPRITE1C
.globalzp SPRITE1D
.globalzp SPRITE1E
.globalzp SPRITE1F
.globalzp SPRITE20
.globalzp SPRITE21
.globalzp SPRITE22
.globalzp SPRITE23
.globalzp SPRITE24
.globalzp SPRITE25
.globalzp SPRITE26
.globalzp SPRITE27
.globalzp SPRITE28
.globalzp SPRITE29
.globalzp SPRITE2a
.globalzp SPRITE2b
.globalzp SPRITE2c
.globalzp SPRITE2d
.globalzp SPRITE2e
.globalzp SPRITE2f

.globalzp ANIMATION01
.globalzp ANIMATION02
.globalzp ANIMATION03
.globalzp ANIMATION04
.globalzp ANIMATION05
.globalzp ANIMATION06
.globalzp ANIMATION07
.globalzp ANIMATION08
.globalzp ANIMATION09
.globalzp ANIMATION0A
.globalzp ANIMATION0B
.globalzp ANIMATION0C
.globalzp ANIMATION0D
.globalzp ANIMATION0E
.globalzp ANIMATION0F

;address table
.global Sprites_l
.global Sprites_h
.global Animations_l
.global Animations_h
